tlt_organization_unit_service_type_api:
    resource: "@TltOrganizationUnitBundle/Controller/Api/Rest/ServiceTypeController.php"
    type: rest
tlt_organization_unit_service_type_services_api:
    resource: "@TltOrganizationUnitBundle/Controller/Api/Rest/ServiceTypeServicesController.php"
    type: rest
tlt_organization_unit_service_api:
    resource: "@TltOrganizationUnitBundle/Controller/Api/Rest/ServiceController.php"
    type: rest
tlt_organization_unit_tel_entity_api:
    resource: "@TltOrganizationUnitBundle/Controller/Api/Rest/TELEntityController.php"
    type: rest
tlt_organization_unit_tlt_entity_api:
    resource: "@TltOrganizationUnitBundle/Controller/Api/Rest/TLTEntityController.php"
    type: rest
tlt_organization_unit_general_location_api:
    resource: "@TltOrganizationUnitBundle/Controller/Api/Rest/GeneralLocationController.php"
    type: rest
tlt_organization_unit_tlt_location_api:
    resource: "@TltOrganizationUnitBundle/Controller/Api/Rest/TLTLocationController.php"
    type: rest
tlt_organization_unit_announcer_api:
    resource: "@TltOrganizationUnitBundle/Controller/Api/Rest/AnnouncerController.php"
    type: rest
tlt_organization_unit_system_api:
    resource: "@TltOrganizationUnitBundle/Controller/Api/Rest/SystemController.php"
    type: rest
tlt_organization_unit_working_schedule_api:
    resource: "@TltOrganizationUnitBundle/Controller/Api/Rest/WorkingScheduleController.php"
    type: rest
tlt_organization_unit_guaranteed_value_api:
    resource: "@TltOrganizationUnitBundle/Controller/Api/Rest/GuaranteedValueController.php"
    type: rest
tlt_organization_unit_equipment_api:
    resource: "@TltOrganizationUnitBundle/Controller/Api/Rest/EquipmentController.php"
    type: rest
tlt_organization_unit_business_unit_tlt_locations_api:
    resource: "@TltOrganizationUnitBundle/Controller/Api/Rest/BusinessUnitTLTLocationsController.php"
    type: rest
