oro_menu_config:
    items:
        tlt_organization_unit_tab:
            label: tlt.organizationunit.menu.tab.label
            uri:   '#'
            extras:
                position: 1
                description: All orgnaization units
        tlt_organization_unit_service_type_index:
            label: tlt.organizationunit.servicetype.menu.index.label
            route: tlt_organization_unit_service_type_index
        tlt_organization_unit_service_index:
            label: tlt.organizationunit.service.menu.index.label
            route: tlt_organization_unit_service_index
        tlt_organization_unit_tel_entity_index:
            label: tlt.organizationunit.telentity.menu.index.label
            route: tlt_organization_unit_tel_entity_index
        tlt_organization_unit_tlt_entity_index:
            label: tlt.organizationunit.tltentity.menu.index.label
            route: tlt_organization_unit_tlt_entity_index
        tlt_organization_unit_general_location_index:
            label: tlt.organizationunit.generallocation.menu.index.label
            route: tlt_organization_unit_general_location_index
        tlt_organization_unit_tlt_location_index:
            label: tlt.organizationunit.tltlocation.menu.index.label
            route: tlt_organization_unit_tlt_location_index
        tlt_organization_unit_announcer_index:
            label: tlt.organizationunit.announcer.menu.index.label
            route: tlt_organization_unit_announcer_index
    tree:
        application_menu:
            children:
                tlt_organization_unit_tab:
                    children:
                        tlt_organization_unit_service_type_index: ~
                        tlt_organization_unit_service_index: ~
                        tlt_organization_unit_tel_entity_index: ~
                        tlt_organization_unit_tlt_entity_index: ~
                        tlt_organization_unit_general_location_index: ~
                        tlt_organization_unit_tlt_location_index: ~
                        tlt_organization_unit_announcer_index: ~