
<%= (created ? 'datagrid: ' : '') %>
    base-<%= entity_name %>-grid:
        source:
            type: orm
            acl_resource: <%= bundle_name %>_<%= entity_name %>_view
            query:
                select:
                    - <%= entityName%>.id
                from:
                    - { table: %<%= bundle_name %>_<%= entity_name %>.entity.class%, alias: <%= entityName %> }
                #join:
                #    left:
        columns:

        sorters:
            columns:

            default:

        filters:
            columns:

        properties:
            id: ~
            view_link:
                type:         url
                route:        <%= bundle_name %>_<%= entity_name %>_view
                params:       [ id ]
            update_link:
                type:         url
                route:        <%= bundle_name %>_<%= entity_name %>_update
                params:       [ id ]
            delete_link:
                type:         url
                route:        <%= bundle_name %>_<%= entity_name %>_api_delete_<%= entity_name %>
                params:       [ id ]
        actions:
            view:
                type:         navigate
                acl_resource: <%= bundle_name %>_<%= entity_name %>_view
                label:        oro.grid.action.view
                icon:         eye-open
                link:         view_link
                rowAction:    true
            update:
                type:         navigate
                acl_resource: <%= bundle_name %>_<%= entity_name %>_update
                label:        oro.grid.action.update
                icon:         edit
                link:         update_link
            delete:
                type:         delete
                acl_resource: <%= bundle_name %>_<%= entity_name %>_delete
                label:        oro.grid.action.delete
                icon:         trash
                link:         delete_link
    <%= entity_name %>-grid:
        extends: base-<%= entity_name %>-grid
        filters:
            columns:
